export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_FILE = 'SAVE_FILE';
export const GET_SOURCE_CODE = 'GET_SOURCE_CODE';
export const GET_FILE_DIRECTORIES = 'GET_FILE_DIRECTORIES';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
export const TOGGLE_MUST_SAVE = 'TOGGLE_MUST_SAVE';
